### ISSUE TITLE
Bot can ping users, roles and @everyone/@here

### ISSUE THREAD

**Issue by vicky5124** [isakvik/waifubot#3]
There is no blacklist set to pings (or just `@`), so people can send `!pic @everyone` and then delete their message, and the bot will have pinged everyone.

everyone: https://i.imgur.com/vFp70Lq.png
user: https://i.imgur.com/43gsjGv.png

Making the waifubot role unable to ping everyone wouldn't fix the user and group pings. So the best solution would be to blacklist pings or the character `@`

**Comment by isakvik** [comment]
should be good
